// <auto-generated />
using System;
using EvoWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvoWebsite.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20210415022400_NotFinal")]
    partial class NotFinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("EvoWebsite.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MSRP")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            ImgPath = "/img/Super/Adder.png",
                            MSRP = 0.0,
                            Name = "Adder",
                            Price = 435000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 2,
                            ImgPath = "/img/Super/Bullet.png",
                            MSRP = 0.0,
                            Name = "Bullet",
                            Price = 175000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 3,
                            ImgPath = "/img/Super/Cheetah.png",
                            MSRP = 0.0,
                            Name = "Cheetah",
                            Price = 300000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 4,
                            ImgPath = "/img/Super/EntityXF.png",
                            MSRP = 0.0,
                            Name = "Entity XF",
                            Price = 375000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 5,
                            ImgPath = "/img/Super/Infernus.png",
                            MSRP = 0.0,
                            Name = "Infernus",
                            Price = 175000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 6,
                            ImgPath = "/img/Super/Osiris.png",
                            MSRP = 0.0,
                            Name = "Osiris",
                            Price = 350000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 7,
                            ImgPath = "/img/Super/T20.png",
                            MSRP = 0.0,
                            Name = "T20",
                            Price = 400000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 8,
                            ImgPath = "/img/Super/TurismoR.png",
                            MSRP = 0.0,
                            Name = "Turismo R",
                            Price = 300000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 9,
                            ImgPath = "/img/Super/Vacca.png",
                            MSRP = 0.0,
                            Name = "Vacca",
                            Price = 125000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 10,
                            ImgPath = "/img/Super/Voltic.png",
                            MSRP = 0.0,
                            Name = "Voltic",
                            Price = 175000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 11,
                            ImgPath = "/img/Super/Zentorno.png",
                            MSRP = 0.0,
                            Name = "Zentorno",
                            Price = 300000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 189,
                            ImgPath = "/img/Super/Banshee900R.png",
                            MSRP = 0.0,
                            Name = "Banshee 900R Bravado",
                            Price = 160000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 190,
                            ImgPath = "/img/Super/Autarch.png",
                            MSRP = 0.0,
                            Name = "Autarch",
                            Price = 475000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 191,
                            ImgPath = "/img/Super/EntityXXR.png",
                            MSRP = 0.0,
                            Name = "Entity XXR",
                            Price = 450000.0,
                            Type = "Super"
                        },
                        new
                        {
                            CarId = 12,
                            ImgPath = "/img/Sport/9F.png",
                            MSRP = 0.0,
                            Name = "9F",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 13,
                            ImgPath = "/img/Sport/9FCabrio.png",
                            MSRP = 0.0,
                            Name = "9F Cabrio",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 14,
                            ImgPath = "/img/Sport/Alpha.png",
                            MSRP = 0.0,
                            Name = "Alpha",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 15,
                            ImgPath = "/img/Sport/Banshee.png",
                            MSRP = 0.0,
                            Name = "Banshee",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 16,
                            ImgPath = "/img/Sport/BlistaCompact.png",
                            MSRP = 0.0,
                            Name = "Blista Compact",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 17,
                            ImgPath = "/img/Sport/GoGoMonkeyBlista.png",
                            MSRP = 0.0,
                            Name = "Monkey Blista",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 18,
                            ImgPath = "/img/Sport/Buffalo.png",
                            MSRP = 0.0,
                            Name = "Buffalo",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 19,
                            ImgPath = "/img/Sport/BuffaloS.png",
                            MSRP = 0.0,
                            Name = "Buffalo S",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 20,
                            ImgPath = "/img/Sport/SprunkBuffalo.png",
                            MSRP = 0.0,
                            Name = "Sprunk Buffalo",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 21,
                            ImgPath = "/img/Sport/Carbonizzare.png",
                            MSRP = 0.0,
                            Name = "Carbonizzare",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 22,
                            ImgPath = "/img/Sport/Comet.png",
                            MSRP = 0.0,
                            Name = "Comet",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 23,
                            ImgPath = "/img/Sport/Coquette.png",
                            MSRP = 0.0,
                            Name = "Coquette",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 24,
                            ImgPath = "/img/Sport/ElegyRH8.png",
                            MSRP = 0.0,
                            Name = "Elegy RH8",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 25,
                            ImgPath = "/img/Sport/Feltzer.png",
                            MSRP = 0.0,
                            Name = "Feltzer",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 26,
                            ImgPath = "/img/Sport/FuroreGT.png",
                            MSRP = 0.0,
                            Name = "Furore GT",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 27,
                            ImgPath = "/img/Sport/Fusilade.png",
                            MSRP = 0.0,
                            Name = "Fusilade",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 28,
                            ImgPath = "/img/Sport/Futo.png",
                            MSRP = 0.0,
                            Name = "Futo",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 29,
                            ImgPath = "/img/Sport/Jester.png",
                            MSRP = 0.0,
                            Name = "Jester",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 30,
                            ImgPath = "/img/Sport/Jesterdecourse.png",
                            MSRP = 0.0,
                            Name = "Jester 2",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 31,
                            ImgPath = "/img/Sport/Massacro.png",
                            MSRP = 0.0,
                            Name = "Massacro",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 32,
                            ImgPath = "/img/Sport/Massacrodecourse.png",
                            MSRP = 0.0,
                            Name = "Massacro 2",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 33,
                            ImgPath = "/img/Sport/Penumbra.png",
                            MSRP = 0.0,
                            Name = "Penumbra",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 34,
                            ImgPath = "/img/Sport/RapidGT.png",
                            MSRP = 0.0,
                            Name = "Rapid GT",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 35,
                            ImgPath = "/img/Sport/Schwartzer.png",
                            MSRP = 0.0,
                            Name = "Schwartzer",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 36,
                            ImgPath = "/img/Sport/Sultan.png",
                            MSRP = 0.0,
                            Name = "Sultan",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 37,
                            ImgPath = "/img/Sport/Surano.png",
                            MSRP = 0.0,
                            Name = "Surano",
                            Price = 0.0,
                            Type = "Sport"
                        },
                        new
                        {
                            CarId = 38,
                            ImgPath = "/img/SportClassics/CoquetteClassic.png",
                            MSRP = 0.0,
                            Name = "Coquette Ci",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 39,
                            ImgPath = "/img/SportClassics/JB700.png",
                            MSRP = 0.0,
                            Name = "JB700",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 40,
                            ImgPath = "/img/SportClassics/Manana.png",
                            MSRP = 0.0,
                            Name = "Manana",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 41,
                            ImgPath = "/img/SportClassics/Monroe.png",
                            MSRP = 0.0,
                            Name = "Monroe",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 42,
                            ImgPath = "/img/SportClassics/Peyote.png",
                            MSRP = 0.0,
                            Name = "Peyote",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 43,
                            ImgPath = "/img/SportClassics/Pigalle.png",
                            MSRP = 0.0,
                            Name = "Pigalle",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 44,
                            ImgPath = "/img/SportClassics/Roosevelt.png",
                            MSRP = 0.0,
                            Name = "Roosevelt",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 45,
                            ImgPath = "/img/SportClassics/Stinger.png",
                            MSRP = 0.0,
                            Name = "Stinger",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 46,
                            ImgPath = "/img/SportClassics/StirlingGT.png",
                            MSRP = 0.0,
                            Name = "Stirling GT",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 47,
                            ImgPath = "/img/SportClassics/Tornado.png",
                            MSRP = 0.0,
                            Name = "Tornado",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 48,
                            ImgPath = "/img/SportClassics/Z-Type.png",
                            MSRP = 0.0,
                            Name = "Z-Type",
                            Price = 0.0,
                            Type = "SportClassics"
                        },
                        new
                        {
                            CarId = 49,
                            ImgPath = "/img/Sedans/Asea.png",
                            MSRP = 0.0,
                            Name = "Asea",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 50,
                            ImgPath = "/img/Sedans/Asterope.png",
                            MSRP = 0.0,
                            Name = "Asterope",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 51,
                            ImgPath = "/img/Sedans/Emperor.png",
                            MSRP = 0.0,
                            Name = "Emperor",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 52,
                            ImgPath = "/img/Sedans/Fugitive.png",
                            MSRP = 0.0,
                            Name = "Fugitive",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 53,
                            ImgPath = "/img/Sedans/Glendale.png",
                            MSRP = 0.0,
                            Name = "Glendale",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 54,
                            ImgPath = "/img/Sedans/Ingot.png",
                            MSRP = 0.0,
                            Name = "Ingot",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 55,
                            ImgPath = "/img/Sedans/Intruder.png",
                            MSRP = 0.0,
                            Name = "Intruder",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 56,
                            ImgPath = "/img/Sedans/Premier.png",
                            MSRP = 0.0,
                            Name = "Premier ",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 57,
                            ImgPath = "/img/Sedans/Primo.png",
                            MSRP = 0.0,
                            Name = "Primo",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 58,
                            ImgPath = "/img/Sedans/Regina.png",
                            MSRP = 0.0,
                            Name = "Premier",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 59,
                            ImgPath = "/img/Sedans/RomeroHearse.png",
                            MSRP = 0.0,
                            Name = "Romero Hearse",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 60,
                            ImgPath = "/img/Sedans/Schafter.png",
                            MSRP = 0.0,
                            Name = "Schafter",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 61,
                            ImgPath = "/img/Sedans/Stanier.png",
                            MSRP = 0.0,
                            Name = "Stanier",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 62,
                            ImgPath = "/img/Sedans/Stratum.png",
                            MSRP = 0.0,
                            Name = "Stratum",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 63,
                            ImgPath = "/img/Sedans/Stretch.png",
                            MSRP = 0.0,
                            Name = "Stretch",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 64,
                            ImgPath = "/img/Sedans/SuperDiamond.png",
                            MSRP = 0.0,
                            Name = "Super Diamond",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 65,
                            ImgPath = "/img/Sedans/Surge.png",
                            MSRP = 0.0,
                            Name = "Surge",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 66,
                            ImgPath = "/img/Sedans/Tailgater.png",
                            MSRP = 0.0,
                            Name = "Tailgater",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 67,
                            ImgPath = "/img/Sedans/Warrener.png",
                            MSRP = 0.0,
                            Name = "Warrener",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 68,
                            ImgPath = "/img/Sedans/Washington.png",
                            MSRP = 0.0,
                            Name = "Washington",
                            Price = 0.0,
                            Type = "Sedans"
                        },
                        new
                        {
                            CarId = 69,
                            ImgPath = "/img/Muscle/Blade.png",
                            MSRP = 0.0,
                            Name = "Blade",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 70,
                            ImgPath = "/img/Muscle/Buccaneer.png",
                            MSRP = 0.0,
                            Name = "Buccaneer",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 71,
                            ImgPath = "/img/Muscle/Chino.png",
                            MSRP = 0.0,
                            Name = "Chino",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 72,
                            ImgPath = "/img/Muscle/CoquetteBlackFin.png",
                            MSRP = 0.0,
                            Name = "Coquette BF",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 73,
                            ImgPath = "/img/Muscle/Dominator.png",
                            MSRP = 0.0,
                            Name = "Dominator",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 74,
                            ImgPath = "/img/Muscle/PisswasserDominator.png",
                            MSRP = 0.0,
                            Name = "Dominator 2",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 75,
                            ImgPath = "/img/Muscle/Dukes.png",
                            MSRP = 0.0,
                            Name = "Dukes",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 76,
                            ImgPath = "/img/Muscle/Gauntlet.png",
                            MSRP = 0.0,
                            Name = "Gauntlet",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 77,
                            ImgPath = "/img/Muscle/RedwoodGauntlet.png",
                            MSRP = 0.0,
                            Name = "Gauntlet 2",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 78,
                            ImgPath = "/img/Muscle/Hotknife.png",
                            MSRP = 0.0,
                            Name = "Hotknife",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 79,
                            ImgPath = "/img/Muscle/Phoenix.png",
                            MSRP = 0.0,
                            Name = "Phoenix",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 80,
                            ImgPath = "/img/Muscle/Picador.png",
                            MSRP = 0.0,
                            Name = "Picador",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 81,
                            ImgPath = "/img/Muscle/Rat-Loader.png",
                            MSRP = 0.0,
                            Name = "Rat-Loader",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 82,
                            ImgPath = "/img/Muscle/Rat-Truck.png",
                            MSRP = 0.0,
                            Name = "Rat-Truck",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 83,
                            ImgPath = "/img/Muscle/Ruiner.png",
                            MSRP = 0.0,
                            Name = "Ruiner",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 84,
                            ImgPath = "/img/Muscle/SabreTurbo.png",
                            MSRP = 0.0,
                            Name = "SabreTurbo",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 85,
                            ImgPath = "/img/Muscle/Slamvan.png",
                            MSRP = 0.0,
                            Name = "Slamvan",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 86,
                            ImgPath = "/img/Muscle/Stallion.png",
                            MSRP = 0.0,
                            Name = "Stallion",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 87,
                            ImgPath = "/img/Muscle/BurgerShotStallion.png",
                            MSRP = 0.0,
                            Name = "BS Stallion",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 88,
                            ImgPath = "/img/Muscle/Vigero.png",
                            MSRP = 0.0,
                            Name = "Vigero",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 89,
                            ImgPath = "/img/Muscle/Virgo.png",
                            MSRP = 0.0,
                            Name = "Virgo",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 90,
                            ImgPath = "/img/Muscle/Voodoo.png",
                            MSRP = 0.0,
                            Name = "Voodoo",
                            Price = 0.0,
                            Type = "Muscle"
                        },
                        new
                        {
                            CarId = 91,
                            ImgPath = "/img/Coupes/CognoscentiCabrio.png",
                            MSRP = 0.0,
                            Name = "Cognoscenti",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 92,
                            ImgPath = "/img/Coupes/Exemplar.png",
                            MSRP = 0.0,
                            Name = "Exemplar",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 93,
                            ImgPath = "/img/Coupes/F620.png",
                            MSRP = 0.0,
                            Name = "F620",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 94,
                            ImgPath = "/img/Coupes/Felon.png",
                            MSRP = 0.0,
                            Name = "Felon",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 95,
                            ImgPath = "/img/Coupes/FelonGT.png",
                            MSRP = 0.0,
                            Name = "Felon GT",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 96,
                            ImgPath = "/img/Coupes/Jackal.png",
                            MSRP = 0.0,
                            Name = "Jackal",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 97,
                            ImgPath = "/img/Coupes/Oracle.png",
                            MSRP = 0.0,
                            Name = "Oracle",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 98,
                            ImgPath = "/img/Coupes/OracleXS.png",
                            MSRP = 0.0,
                            Name = "Oracle XS",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 99,
                            ImgPath = "/img/Coupes/Sentinel.png",
                            MSRP = 0.0,
                            Name = "Sentinel",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 100,
                            ImgPath = "/img/Coupes/SentinelXS.png",
                            MSRP = 0.0,
                            Name = "Sentinel XS",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 101,
                            ImgPath = "/img/Coupes/Windsor.png",
                            MSRP = 0.0,
                            Name = "Windsor",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 102,
                            ImgPath = "/img/Coupes/Zion.png",
                            MSRP = 0.0,
                            Name = "Zion",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 103,
                            ImgPath = "/img/Coupes/ZionCabrio.png",
                            MSRP = 0.0,
                            Name = "ZionCabrio",
                            Price = 0.0,
                            Type = "Coupe"
                        },
                        new
                        {
                            CarId = 104,
                            ImgPath = "/img/Compacts/Blista.png",
                            MSRP = 0.0,
                            Name = "Blista",
                            Price = 0.0,
                            Type = "Compact"
                        },
                        new
                        {
                            CarId = 105,
                            ImgPath = "/img/Compacts/Dilettante.png",
                            MSRP = 0.0,
                            Name = "Dilettante",
                            Price = 0.0,
                            Type = "Compact"
                        },
                        new
                        {
                            CarId = 106,
                            ImgPath = "/img/Compacts/Issi.png",
                            MSRP = 0.0,
                            Name = "Issi",
                            Price = 0.0,
                            Type = "Compact"
                        },
                        new
                        {
                            CarId = 107,
                            ImgPath = "/img/Compacts/Panto.png",
                            MSRP = 0.0,
                            Name = "Panto",
                            Price = 0.0,
                            Type = "Compact"
                        },
                        new
                        {
                            CarId = 108,
                            ImgPath = "/img/Compacts/Prairie.png",
                            MSRP = 0.0,
                            Name = "Prairie",
                            Price = 0.0,
                            Type = "Compact"
                        },
                        new
                        {
                            CarId = 109,
                            ImgPath = "/img/Compacts/Rhapsody.png",
                            MSRP = 0.0,
                            Name = "Rhapsody",
                            Price = 0.0,
                            Type = "Compact"
                        },
                        new
                        {
                            CarId = 110,
                            ImgPath = "/img/SUVs/Baller.png",
                            MSRP = 0.0,
                            Name = "Baller",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 111,
                            ImgPath = "/img/SUVs/Baller2.png",
                            MSRP = 0.0,
                            Name = "Baller2",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 112,
                            ImgPath = "/img/SUVs/BeeJayXL.png",
                            MSRP = 0.0,
                            Name = "BeeJay XL",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 113,
                            ImgPath = "/img/SUVs/Cavalcade.png",
                            MSRP = 0.0,
                            Name = "Cavalcade",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 114,
                            ImgPath = "/img/SUVs/Cavalcade2.png",
                            MSRP = 0.0,
                            Name = "Cavalcade 2",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 115,
                            ImgPath = "/img/SUVs/Dubsta.png",
                            MSRP = 0.0,
                            Name = "Dubsta",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 116,
                            ImgPath = "/img/SUVs/Dubsta2.png",
                            MSRP = 0.0,
                            Name = "Dubsta2",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 117,
                            ImgPath = "/img/SUVs/FQ2.png",
                            MSRP = 0.0,
                            Name = "FQ2",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 118,
                            ImgPath = "/img/SUVs/Granger.png",
                            MSRP = 0.0,
                            Name = "Granger",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 119,
                            ImgPath = "/img/SUVs/Gresley.png",
                            MSRP = 0.0,
                            Name = "Gresley",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 120,
                            ImgPath = "/img/SUVs/Habanero.png",
                            MSRP = 0.0,
                            Name = "Habanero",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 121,
                            ImgPath = "/img/SUVs/HuntleyS.png",
                            MSRP = 0.0,
                            Name = "Huntley S",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 122,
                            ImgPath = "/img/SUVs/Landstalker.png",
                            MSRP = 0.0,
                            Name = "Landstalker",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 123,
                            ImgPath = "/img/SUVs/Mesa.png",
                            MSRP = 0.0,
                            Name = "Mesa",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 124,
                            ImgPath = "/img/SUVs/Mesa3.png",
                            MSRP = 0.0,
                            Name = "Mesa 3",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 125,
                            ImgPath = "/img/SUVs/Patriot.png",
                            MSRP = 0.0,
                            Name = "Patriot",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 126,
                            ImgPath = "/img/SUVs/Radius.png",
                            MSRP = 0.0,
                            Name = "Radius",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 127,
                            ImgPath = "/img/SUVs/Rocoto.png",
                            MSRP = 0.0,
                            Name = "Rocoto",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 128,
                            ImgPath = "/img/SUVs/Seminole.png",
                            MSRP = 0.0,
                            Name = "Seminole",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 129,
                            ImgPath = "/img/SUVs/Serrano.png",
                            MSRP = 0.0,
                            Name = "Serrano",
                            Price = 0.0,
                            Type = "SUV"
                        },
                        new
                        {
                            CarId = 130,
                            ImgPath = "/img/Vans/Bison.png",
                            MSRP = 0.0,
                            Name = "Bison",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 131,
                            ImgPath = "/img/Vans/Bison2.png",
                            MSRP = 0.0,
                            Name = "Bison2",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 132,
                            ImgPath = "/img/Vans/Bison3.png",
                            MSRP = 0.0,
                            Name = "Bison3",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 133,
                            ImgPath = "/img/Vans/BobcatXL.png",
                            MSRP = 0.0,
                            Name = "Bobcat XL",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 134,
                            ImgPath = "/img/Vans/Boxville.png",
                            MSRP = 0.0,
                            Name = "Boxville",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 135,
                            ImgPath = "/img/Vans/Boxville2.png",
                            MSRP = 0.0,
                            Name = "Boxville 2",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 136,
                            ImgPath = "/img/Vans/Boxville3.png",
                            MSRP = 0.0,
                            Name = "Boxville 3",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 137,
                            ImgPath = "/img/Vans/Burrito.png",
                            MSRP = 0.0,
                            Name = "Burrito",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 138,
                            ImgPath = "/img/Vans/Camper.png",
                            MSRP = 0.0,
                            Name = "Camper",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 139,
                            ImgPath = "/img/Vans/GangBurrito.png",
                            MSRP = 0.0,
                            Name = "Gang Burrito",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 140,
                            ImgPath = "/img/Vans/GangBurrito2.png",
                            MSRP = 0.0,
                            Name = "Gang Burrito 2",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 141,
                            ImgPath = "/img/Vans/Journey.png",
                            MSRP = 0.0,
                            Name = "Journey",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 142,
                            ImgPath = "/img/Vans/Minivan.png",
                            MSRP = 0.0,
                            Name = "Minivan",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 143,
                            ImgPath = "/img/Vans/Paradise.png",
                            MSRP = 0.0,
                            Name = "Paradise",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 144,
                            ImgPath = "/img/Vans/Pony.png",
                            MSRP = 0.0,
                            Name = "Pony",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 145,
                            ImgPath = "/img/Vans/Rumpo.png",
                            MSRP = 0.0,
                            Name = "Rumpo",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 146,
                            ImgPath = "/img/Vans/Speedo.png",
                            MSRP = 0.0,
                            Name = "Speedo",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 147,
                            ImgPath = "/img/Vans/Surfer.png",
                            MSRP = 0.0,
                            Name = "Surfer",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 148,
                            ImgPath = "/img/Vans/Surfer2.png",
                            MSRP = 0.0,
                            Name = "Surfer 2",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 149,
                            ImgPath = "/img/Vans/TacoVan.png",
                            MSRP = 0.0,
                            Name = "TacoVan",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 150,
                            ImgPath = "/img/Vans/Youga.png",
                            MSRP = 0.0,
                            Name = "Youga",
                            Price = 0.0,
                            Type = "Van"
                        },
                        new
                        {
                            CarId = 152,
                            ImgPath = "/img/Off-Road/Bifta.png",
                            MSRP = 0.0,
                            Name = "Bifta",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 153,
                            ImgPath = "/img/Off-Road/Blazer.png",
                            MSRP = 0.0,
                            Name = "Blazer",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 154,
                            ImgPath = "/img/Off-Road/BlazerLifeguard.png",
                            MSRP = 0.0,
                            Name = "Blazer Lifeguard",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 155,
                            ImgPath = "/img/Off-Road/Bodhi.png",
                            MSRP = 0.0,
                            Name = "Bodhi",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 156,
                            ImgPath = "/img/Off-Road/Brawler.png",
                            MSRP = 0.0,
                            Name = "Brawler",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 157,
                            ImgPath = "/img/Off-Road/Dubsta6x6.png",
                            MSRP = 0.0,
                            Name = "Dubsta 6x6",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 158,
                            ImgPath = "/img/Off-Road/DuneBuggy.png",
                            MSRP = 0.0,
                            Name = "Dune Buggy",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 159,
                            ImgPath = "/img/Off-Road/Duneloader.png",
                            MSRP = 0.0,
                            Name = "Duneloader",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 160,
                            ImgPath = "/img/Off-Road/HotRodBlazer.png",
                            MSRP = 0.0,
                            Name = "Hot Rod Blazer",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 161,
                            ImgPath = "/img/Off-Road/Injection.png",
                            MSRP = 0.0,
                            Name = "Injection",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 162,
                            ImgPath = "/img/Off-Road/Kalahari.png",
                            MSRP = 0.0,
                            Name = "Kalahari",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 163,
                            ImgPath = "/img/Off-Road/Marshall.png",
                            MSRP = 0.0,
                            Name = "Marshall",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 164,
                            ImgPath = "/img/Off-Road/RancherXL.png",
                            MSRP = 0.0,
                            Name = "Rancher XL",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 165,
                            ImgPath = "/img/Off-Road/Rebel.png",
                            MSRP = 0.0,
                            Name = "Rebel",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 166,
                            ImgPath = "/img/Off-Road/RustyRebel.png",
                            MSRP = 0.0,
                            Name = "Rusty Rebel",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 167,
                            ImgPath = "/img/Off-Road/SandkingXL.png",
                            MSRP = 0.0,
                            Name = "Sandking XL",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 168,
                            ImgPath = "/img/Off-Road/SandkingSWB.png",
                            MSRP = 0.0,
                            Name = "Sandking SWB",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 169,
                            ImgPath = "/img/Off-Road/Liberator.png",
                            MSRP = 0.0,
                            Name = "Liberator",
                            Price = 0.0,
                            Type = "Offroad"
                        },
                        new
                        {
                            CarId = 170,
                            ImgPath = "/img/Motorcycles/Akuma.png",
                            MSRP = 0.0,
                            Name = "Akuma",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 171,
                            ImgPath = "/img/Motorcycles/Bagger.png",
                            MSRP = 0.0,
                            Name = "Bagger",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 172,
                            ImgPath = "/img/Motorcycles/Bati801.png",
                            MSRP = 0.0,
                            Name = "Bati 801",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 173,
                            ImgPath = "/img/Motorcycles/Bati801RR.png",
                            MSRP = 0.0,
                            Name = "Bati 801 RR",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 174,
                            ImgPath = "/img/Motorcycles/CarbonRS.png",
                            MSRP = 0.0,
                            Name = "Carbon RS",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 175,
                            ImgPath = "/img/Motorcycles/Daemon.png",
                            MSRP = 0.0,
                            Name = "Daemon",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 176,
                            ImgPath = "/img/Motorcycles/DoubleT.png",
                            MSRP = 0.0,
                            Name = "Double T",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 177,
                            ImgPath = "/img/Motorcycles/Faggio.png",
                            MSRP = 0.0,
                            Name = "Faggio",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 178,
                            ImgPath = "/img/Motorcycles/Hakuchou.png",
                            MSRP = 0.0,
                            Name = "Hakuchou",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 179,
                            ImgPath = "/img/Motorcycles/Hexer.png",
                            MSRP = 0.0,
                            Name = "Hexer",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 180,
                            ImgPath = "/img/Motorcycles/Innovation.png",
                            MSRP = 0.0,
                            Name = "Innovation",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 181,
                            ImgPath = "/img/Motorcycles/Nemesis.png",
                            MSRP = 0.0,
                            Name = "Nemesis",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 182,
                            ImgPath = "/img/Motorcycles/PCJ600.png",
                            MSRP = 0.0,
                            Name = "PCJ600",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 183,
                            ImgPath = "/img/Motorcycles/Ruffian.png",
                            MSRP = 0.0,
                            Name = "Ruffian",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 184,
                            ImgPath = "/img/Motorcycles/Sanchez.png",
                            MSRP = 0.0,
                            Name = "Sanchez",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 185,
                            ImgPath = "/img/Motorcycles/Sovereign.png",
                            MSRP = 0.0,
                            Name = "Sovereign",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 186,
                            ImgPath = "/img/Motorcycles/Thrust.png",
                            MSRP = 0.0,
                            Name = "Thrust",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 187,
                            ImgPath = "/img/Motorcycles/Vader.png",
                            MSRP = 0.0,
                            Name = "Vader",
                            Price = 0.0,
                            Type = "Moto"
                        },
                        new
                        {
                            CarId = 188,
                            ImgPath = "/img/Motorcycles/Vindicator.png",
                            MSRP = 0.0,
                            Name = "Vindicator",
                            Price = 0.0,
                            Type = "Moto"
                        });
                });

            modelBuilder.Entity("EvoWebsite.Models.Importe", b =>
                {
                    b.Property<int>("ImporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.HasKey("ImporteId");

                    b.ToTable("Importes");
                });

            modelBuilder.Entity("EvoWebsite.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
